{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "CPU times: user 52 µs, sys: 5 µs, total: 57 µs\n",
      "Wall time: 63.4 µs\n"
     ]
    }
   ],
   "source": [
    "%%time\n",
    "import os \n",
    "os.chdir(\"../\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Logging to ./log/cityscapes/resnet_fcn_asp3_mep16384(183654)_deepbase_resnet101_dilated8.log\n",
      "World size: 4\n",
      "['--data_dir', '../../input/openseg-cityscapes-gtfine', '--drop_last', 'y', '--phase', 'test', '--gathered', 'n', '--loss_balance', 'y', '--log_to_file', 'n', '--pretrained', '../../input/pre-trained/resnet101-imagenet-openseg.pth', '--configs', 'configs/cityscapes/R_101_D_8.json', '--checkpoints_name', 'resnet_fcn_asp3_mep16384(183654)_deepbase_resnet101_dilated8', '--backbone', 'deepbase_resnet101_dilated8', '--model_name', 'resnet_fcn_asp3_mep', '--loss_type', 'fs_auxce_loss_dc', '--max_iters', '40000', '--workers', '4', '--gpu', '2', '3', '4', '5', '--distribute', '--train_batch_size', '8', '--val_batch_size', '4', '--projector', 'layer_2', 'layer_3', 'layer_4', '--memory_size', '16384', '--test_dir', '../../input/openseg-cityscapes-gtfine/val/image', '--out_dir', './results/resnet_fcn_asp3_mep16384(183654)_deepbase_resnet101_dilated8_val_ss', '--resume', './val/dchp.pth']\n",
      "/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/distributed/launch.py:186: FutureWarning: The module torch.distributed.launch is deprecated\n",
      "and will be removed in future. Use torchrun.\n",
      "Note that --use_env is set by default in torchrun.\n",
      "If your script expects `--local_rank` argument to be set, please\n",
      "change it to read from `os.environ['LOCAL_RANK']` instead. See \n",
      "https://pytorch.org/docs/stable/distributed.html#launch-utility for \n",
      "further instructions\n",
      "\n",
      "  FutureWarning,\n",
      "WARNING:torch.distributed.run:\n",
      "*****************************************\n",
      "Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. \n",
      "*****************************************\n",
      "2023-06-01 08:09:46,759 INFO    [offset_helper.py, 54] engery/max-distance: 5 engery/min-distance: 0\n",
      "2023-06-01 08:09:46,759 INFO    [offset_helper.py, 61] direction/num_classes: 8 scale: 1\n",
      "2023-06-01 08:09:46,759 INFO    [offset_helper.py, 66] c4 align axis: False\n",
      "2023-06-01 08:09:46,762 INFO    [offset_helper.py, 54] engery/max-distance: 5 engery/min-distance: 0\n",
      "2023-06-01 08:09:46,762 INFO    [offset_helper.py, 61] direction/num_classes: 8 scale: 1\n",
      "2023-06-01 08:09:46,762 INFO    [offset_helper.py, 66] c4 align axis: False\n",
      "2023-06-01 08:09:46,765 INFO    [offset_helper.py, 54] engery/max-distance: 5 engery/min-distance: 0\n",
      "2023-06-01 08:09:46,765 INFO    [offset_helper.py, 61] direction/num_classes: 8 scale: 1\n",
      "2023-06-01 08:09:46,765 INFO    [offset_helper.py, 66] c4 align axis: False\n",
      "2023-06-01 08:09:46,770 INFO    [offset_helper.py, 54] engery/max-distance: 5 engery/min-distance: 0\n",
      "2023-06-01 08:09:46,770 INFO    [offset_helper.py, 61] direction/num_classes: 8 scale: 1\n",
      "2023-06-01 08:09:46,771 INFO    [offset_helper.py, 66] c4 align axis: False\n",
      "2023-06-01 08:09:46,800 INFO    [module_runner.py, 44] BN Type is torchsyncbn.\n",
      "2023-06-01 08:09:46,808 INFO    [module_runner.py, 44] BN Type is torchsyncbn.\n",
      "2023-06-01 08:09:46,815 INFO    [module_runner.py, 44] BN Type is torchsyncbn.\n",
      "2023-06-01 08:09:46,815 INFO    [module_runner.py, 44] BN Type is torchsyncbn.\n",
      "2023-06-01 08:09:47,762 INFO    [module_helper.py, 128] Loading pretrained model:../../input/pre-trained/resnet101-imagenet-openseg.pth\n",
      "2023-06-01 08:09:47,772 INFO    [module_helper.py, 128] Loading pretrained model:../../input/pre-trained/resnet101-imagenet-openseg.pth\n",
      "2023-06-01 08:09:47,840 INFO    [module_helper.py, 128] Loading pretrained model:../../input/pre-trained/resnet101-imagenet-openseg.pth\n",
      "2023-06-01 08:09:47,932 INFO    [module_helper.py, 128] Loading pretrained model:../../input/pre-trained/resnet101-imagenet-openseg.pth\n",
      "2023-06-01 08:10:00,187 INFO    [module_runner.py, 88] Loading checkpoint from ./val/dchp.pth...\n",
      "2023-06-01 08:10:00,187 INFO    [module_runner.py, 88] Loading checkpoint from ./val/dchp.pth...\n",
      "2023-06-01 08:10:00,187 INFO    [module_runner.py, 88] Loading checkpoint from ./val/dchp.pth...\n",
      "2023-06-01 08:10:00,189 INFO    [module_runner.py, 88] Loading checkpoint from ./val/dchp.pth...\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zk/GIT/working/openseg/main.py\", line 555, in <module>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zk/GIT/working/openseg/main.py\", line 555, in <module>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zk/GIT/working/openseg/main.py\", line 555, in <module>\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zk/GIT/working/openseg/main.py\", line 555, in <module>\n",
      "    model = Tester(configer)\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tester.py\", line 74, in __init__\n",
      "    self._init_model()\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tester.py\", line 78, in _init_model\n",
      "    self.seg_net = self.module_runner.load_net(self.seg_net)\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tools/module_runner.py\", line 91, in load_net\n",
      "    resume_dict = torch.load(self.configer.get(\"network\", \"resume\"))\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/serialization.py\", line 705, in load\n",
      "    model = Tester(configer)\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tester.py\", line 74, in __init__\n",
      "    self._init_model()\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tester.py\", line 78, in _init_model\n",
      "        model = Tester(configer)with _open_zipfile_reader(opened_file) as opened_zipfile:\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/serialization.py\", line 242, in __init__\n",
      "\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tester.py\", line 74, in __init__\n",
      "    self.seg_net = self.module_runner.load_net(self.seg_net)\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tools/module_runner.py\", line 91, in load_net\n",
      "    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))\n",
      "RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory\n",
      "    model = Tester(configer)\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tester.py\", line 74, in __init__\n",
      "    resume_dict = torch.load(self.configer.get(\"network\", \"resume\"))\n",
      "    self._init_model()\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/serialization.py\", line 705, in load\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tester.py\", line 78, in _init_model\n",
      "    self._init_model()\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tester.py\", line 78, in _init_model\n",
      "    self.seg_net = self.module_runner.load_net(self.seg_net)\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tools/module_runner.py\", line 91, in load_net\n",
      "    with _open_zipfile_reader(opened_file) as opened_zipfile:\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/serialization.py\", line 242, in __init__\n",
      "    self.seg_net = self.module_runner.load_net(self.seg_net)\n",
      "      File \"/home/zk/GIT/working/openseg/segmentor/tools/module_runner.py\", line 91, in load_net\n",
      "resume_dict = torch.load(self.configer.get(\"network\", \"resume\"))\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/serialization.py\", line 705, in load\n",
      "        resume_dict = torch.load(self.configer.get(\"network\", \"resume\"))super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))\n",
      "\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/serialization.py\", line 705, in load\n",
      "RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory\n",
      "    with _open_zipfile_reader(opened_file) as opened_zipfile:\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/serialization.py\", line 242, in __init__\n",
      "    with _open_zipfile_reader(opened_file) as opened_zipfile:\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/serialization.py\", line 242, in __init__\n",
      "    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))\n",
      "    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))\n",
      "RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory\n",
      "RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory\n",
      "ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 6194) of binary: /home/zk/anaconda3/envs/temp/bin/python\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/distributed/launch.py\", line 193, in <module>\n",
      "    main()\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/distributed/launch.py\", line 189, in main\n",
      "    launch(args)\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/distributed/launch.py\", line 174, in launch\n",
      "    run(args)\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/distributed/run.py\", line 755, in run\n",
      "    )(*cmd_args)\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/distributed/launcher/api.py\", line 131, in __call__\n",
      "    return launch_agent(self._config, self._entrypoint, list(args))\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/distributed/launcher/api.py\", line 247, in launch_agent\n",
      "    failures=result.failures,\n",
      "torch.distributed.elastic.multiprocessing.errors.ChildFailedError: \n",
      "============================================================\n",
      "/home/zk/GIT/working/openseg/main.py FAILED\n",
      "------------------------------------------------------------\n",
      "Failures:\n",
      "[1]:\n",
      "  time      : 2023-06-01_08:10:04\n",
      "  host      : GPU1\n",
      "  rank      : 1 (local_rank: 1)\n",
      "  exitcode  : 1 (pid: 6198)\n",
      "  error_file: <N/A>\n",
      "  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html\n",
      "[2]:\n",
      "  time      : 2023-06-01_08:10:04\n",
      "  host      : GPU1\n",
      "  rank      : 2 (local_rank: 2)\n",
      "  exitcode  : 1 (pid: 6199)\n",
      "  error_file: <N/A>\n",
      "  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html\n",
      "[3]:\n",
      "  time      : 2023-06-01_08:10:04\n",
      "  host      : GPU1\n",
      "  rank      : 3 (local_rank: 3)\n",
      "  exitcode  : 1 (pid: 6200)\n",
      "  error_file: <N/A>\n",
      "  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html\n",
      "------------------------------------------------------------\n",
      "Root Cause (first observed failure):\n",
      "[0]:\n",
      "  time      : 2023-06-01_08:10:04\n",
      "  host      : GPU1\n",
      "  rank      : 0 (local_rank: 0)\n",
      "  exitcode  : 1 (pid: 6194)\n",
      "  error_file: <N/A>\n",
      "  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html\n",
      "============================================================\n",
      "Traceback (most recent call last):\n",
      "  File \"main.py\", line 510, in <module>\n",
      "    handle_distributed(args_parser, os.path.expanduser(os.path.abspath(__file__)))\n",
      "  File \"/home/zk/GIT/working/openseg/lib/utils/distributed.py\", line 61, in handle_distributed\n",
      "    cmd=command_args)    \n",
      "subprocess.CalledProcessError: Command '['/home/zk/anaconda3/envs/temp/bin/python', '-u', '-m', 'torch.distributed.launch', '--master_port=12345', '--nproc_per_node', '4', '/home/zk/GIT/working/openseg/main.py', '--data_dir', '../../input/openseg-cityscapes-gtfine', '--drop_last', 'y', '--phase', 'test', '--gathered', 'n', '--loss_balance', 'y', '--log_to_file', 'n', '--pretrained', '../../input/pre-trained/resnet101-imagenet-openseg.pth', '--configs', 'configs/cityscapes/R_101_D_8.json', '--checkpoints_name', 'resnet_fcn_asp3_mep16384(183654)_deepbase_resnet101_dilated8', '--backbone', 'deepbase_resnet101_dilated8', '--model_name', 'resnet_fcn_asp3_mep', '--loss_type', 'fs_auxce_loss_dc', '--max_iters', '40000', '--workers', '4', '--gpu', '2', '3', '4', '5', '--distribute', '--train_batch_size', '8', '--val_batch_size', '4', '--projector', 'layer_2', 'layer_3', 'layer_4', '--memory_size', '16384', '--test_dir', '../../input/openseg-cityscapes-gtfine/val/image', '--out_dir', './results/resnet_fcn_asp3_mep16384(183654)_deepbase_resnet101_dilated8_val_ss', '--resume', './val/dchp.pth']' returned non-zero exit status 1.\n"
     ]
    }
   ],
   "source": [
    "# [deepbase_resnet101_dilated8] fcnet_dc spatial_ocrnet_dc spatial_asp_ocrnet_mep resnet_fcn_mep\n",
    "!CONFIGS=\"configs/cityscapes/R_101_D_8.json\";DATA_DIR=\"../../input/openseg-cityscapes-gtfine\";\\\n",
    "BACKBONE=\"deepbase_resnet101_dilated8\";PRETRAINED_MODEL=\"../../input/pre-trained/resnet101-imagenet-openseg.pth\";\\\n",
    "MODEL_NAME=\"resnet_fcn_asp3_mep\";\\\n",
    "LOSS_TYPE=\"fs_auxce_loss_dc\";\\\n",
    "MEMORY_SIZE=16384;\\\n",
    "CHECKPOINTS_NAME=\"${MODEL_NAME}${MEMORY_SIZE}(183654)_${BACKBONE}\";LOG_FILE=\"./log/cityscapes/${CHECKPOINTS_NAME}.log\";\\\n",
    "echo \"Logging to $LOG_FILE\";mkdir -p `dirname $LOG_FILE`;\\\n",
    "python -u main.py --data_dir ${DATA_DIR} \\\n",
    "    --drop_last y --phase test --gathered n --loss_balance y --log_to_file n \\\n",
    "    --pretrained ${PRETRAINED_MODEL} --configs ${CONFIGS} --checkpoints_name ${CHECKPOINTS_NAME}  \\\n",
    "    --backbone ${BACKBONE} --model_name ${MODEL_NAME} --loss_type ${LOSS_TYPE}  \\\n",
    "    --max_iters 40000 --workers 4 --gpu 2 3 4 5 --distribute\\\n",
    "    --train_batch_size 8 --val_batch_size 4  \\\n",
    "    --projector \"layer_2\" \"layer_3\" \"layer_4\" \\\n",
    "    --memory_size ${MEMORY_SIZE} \\\n",
    "    --test_dir ${DATA_DIR}/val/image \\\n",
    "    --out_dir ./results/${CHECKPOINTS_NAME}_val_ss\\\n",
    "    --resume ./val/dchp.pth \\\n",
    "    2>&1 | tee ${LOG_FILE}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Logging to ./experiment/log/cityscapes/fcnet16384(183654)_deepbase_resnet101_dilated8_2023-06-01_08-06-59.log\n",
      "2023-06-01 08:07:00,759 INFO    [offset_helper.py, 54] engery/max-distance: 5 engery/min-distance: 0\n",
      "2023-06-01 08:07:00,760 INFO    [offset_helper.py, 61] direction/num_classes: 8 scale: 1\n",
      "2023-06-01 08:07:00,760 INFO    [offset_helper.py, 66] c4 align axis: False\n",
      "2023-06-01 08:07:00,805 INFO    [module_runner.py, 44] BN Type is torchsyncbn.\n",
      "Traceback (most recent call last):\n",
      "  File \"main.py\", line 555, in <module>\n",
      "    model = Tester(configer)\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tester.py\", line 74, in __init__\n",
      "    self._init_model()\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tester.py\", line 78, in _init_model\n",
      "    self.seg_net = self.module_runner.load_net(self.seg_net)\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tools/module_runner.py\", line 76, in load_net\n",
      "    net = self.to_device(net)\n",
      "  File \"/home/zk/GIT/working/openseg/segmentor/tools/module_runner.py\", line 53, in to_device\n",
      "    return_list.append(params[i].to(device))\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 927, in to\n",
      "    return self._apply(convert)\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 579, in _apply\n",
      "    module._apply(fn)\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 579, in _apply\n",
      "    module._apply(fn)\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 579, in _apply\n",
      "    module._apply(fn)\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 602, in _apply\n",
      "    param_applied = fn(param)\n",
      "  File \"/home/zk/anaconda3/envs/temp/lib/python3.7/site-packages/torch/nn/modules/module.py\", line 925, in convert\n",
      "    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)\n",
      "RuntimeError: CUDA error: out of memory\n",
      "CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.\n",
      "For debugging consider passing CUDA_LAUNCH_BLOCKING=1.\n",
      "experiment/val.sh: line 73: -u: command not found\n"
     ]
    }
   ],
   "source": [
    "!bash experiment/val.sh val"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.9.12 ('base')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.16"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "42a4ea106d429adb85b92cbf5fe6fad5ad2431a3e82cdef4435b2cc92f522609"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
